apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-app-dev
  namespace: default
spec:
  chart:
    spec:
      chart: my-app
  values:
    image:
      repository: cdappacr.azurecr.io/my-app
      tag: d04f6080f275d827a0b952a984f5faa73f7bf6a1
