apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend-dev
  namespace: default
spec:
  chart:
    spec:
      chart: backend
  values:
    image:
      repository: cdappacrrgcdapp.azurecr.io/backend
      tag: db0fc8e760b3b93c82856a1dd42b21cc6cfe4237
