apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend-dev
  namespace: default
spec:
  chart:
    spec:
      chart: backend
  values:
    image:
      repository: cdappacrrgcdapp.azurecr.io/backend
      tag: 888b2149df92b07d8cfea8dc5fc1f3b1442df53b
