apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frontend-prod
  namespace: default
spec:
  chart:
    spec:
      chart: frontend
  values:
    image:
      repository: cdappacrrgcdapp.azurecr.io/frontend
      tag: 5f03df411febf9ca403c187c8fe5219677c42d7c
