apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frontend-prod
  namespace: default
spec:
  chart:
    spec:
      chart: frontend
  values:
    image:
      repository: cdappacrrgcdapp.azurecr.io/frontend
      tag: 1e78d1fa942462b311e78f3fceff3232550c4f49
