apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frontend-prod
  namespace: default
spec:
  chart:
    spec:
      chart: frontend
  values:
    image:
      repository: cdappacrrgcdapp.azurecr.io/frontend
      tag: b5c82dea25459439da5143ba28764fdc2e56ddda
