apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend-prod
  namespace: default
spec:
  chart:
    spec:
      chart: backend
  values:
    image:
      repository: cdappacrrgcdapp.azurecr.io/backend
      tag: 283a0c9eadc0f029296f064a2acae95dff20e589
