apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend-prod
  namespace: default
spec:
  chart:
    spec:
      chart: backend
  values:
    image:
      repository: cdappacrrgcdapp.azurecr.io/backend
      tag: dd292d2c562009ba253ce0b4187248530d2874f1
