apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend-prod
  namespace: default
spec:
  chart:
    spec:
      chart: backend
  values:
    image:
      repository: cdappacrrgcdapp.azurecr.io/backend
      tag: a4698ea95e7b529c031d07733b75d01f4b807470
